### ISSUE TITLE
Changes in alacritty.yml schema in Alacritty 0.12

### ISSUE THREAD

**Issue by jraregris** [distinction-dev/alacritty-schema#3]
Hi!

Alacritty recently released a new major version with some changes to the `alacritty.yml`-schema.

It is easy to miss, because I think maybe some the rc-changes was omitted from the main `CHANGELOG.md`.

https://github.com/alacritty/alacritty/releases/tag/v0.12.0-rc1

I have not read everything _thoroughly_, but as far as I can tell (from https://github.com/alacritty/alacritty/releases):
- `alt_send_esc` is out
- `window.option_as_alt` is in
- `window.gtk_theme_variant` is out
- `window.resize_increments` is in
- also changes to values in other options

This is intended more as a heads-up than a request or complaint :).
Have a great day!

**Comment by KillDozerX2** [comment]
Hey Thanks, I will review the new configuration that they've provided and update schema

**Comment by salimhamed** [comment]
Thanks for maintaining this schema, @KillDozerX2! Heads up, I've noticed the missing `window.option_as_alt` options as well when using this schema for yaml validation.

**Comment by KillDozerX2** [comment]
Hey @salimhamed I'm hoping to get to the new schema soon.

**Comment by Freed-Wu** [comment]
And `key_bindings.key` can be a number. See https://github.com/alacritty/alacritty/issues/7253#issuecomment-1741479617

`cursor.style.vi_mode_style` is a legal key. See <https://github.com/alacritty/alacritty/releases/download/v0.12.2/alacritty.yml>

**Comment by tplk** [comment]
I wanted to make a PR with the update, but I noticed that Alacritty is transitioning to TOML for configuration in the next release. Therefore, it seems that this project should be archived in the near future.


> - Configuration file now uses TOML instead of YAML
> Run `alacritty migrate` to automatically convert all configuration files

https://github.com/alacritty/alacritty/releases/tag/v0.13.0-rc1

**Comment by Freed-Wu** [comment]
Even if alacritty change yaml to toml, the configuration should also can use json schema. :smile: IMO, why not move this json schema to alacritty in order to make this json schema keep latest with every publishing of new version with alacritty?

**Comment by KillDozerX2** [comment]
Apologies in missing out on this, I wasn't aware of the fact that TOML extensions like [Event Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml#completion-and-validation-with-json-schema) also support JSON Schema.
We can now close this issue as well.

Thank you all. @tplk & @jraregris have a look at [the TOML extension](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml#completion-and-validation-with-json-schema)
